### ISSUE TITLE
doesn't work in blender 2.93

### ISSUE THREAD

**Issue by erichfrazer** [Fritkot99/AirfoilToolBeta#1]
![image](https://user-images.githubusercontent.com/15388012/133728390-2c3f3c26-ba1a-4950-937a-4c2f4d80277b.png)
when I import 0.5, and then enable it, it says "ModuleNotFoundError: No module named 'AirfoilToolsBeta-0'

**Comment by Fritkot99** [comment]
I found the issue it was a stupid error in the naming of the releases it should be fixed with v0.6 now
